name: Build NetCDF (Windows)
description: Build NetCDF on Windows
runs:
  using: "composite"
  steps:
    - name: Convert line endings
      shell: cmd
      run: |
        unix2dos -n "%GITHUB_WORKSPACE%\modflow6\.github\common\compile_netcdf.bat" "%TEMP%\compile_netcdf.bat"

    - name: Install latest cmake and ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latest
        ninjaVersion: latest

    - name: Setup 7-zip
      uses: milliewalky/setup-7-zip@v1

    - name: Download NetCDF-C
      shell: bash
      run: |
        mkdir -p netcdf/netCDF4.9.2-NC4-64
        cd netcdf/netCDF4.9.2-NC4-64
        curl https://downloads.unidata.ucar.edu/netcdf-c/4.9.2/netCDF4.9.2-NC4-64.exe -O -J
        7z x netCDF4.9.2-NC4-64.exe -aou

    - name: Download NetCDF-Fortran
      shell: bash
      run: |
        mkdir -p netcdf/netcdf-fortran-4.6.1/build
        cd netcdf/netcdf-fortran-4.6.1
        curl https://downloads.unidata.ucar.edu/netcdf-fortran/4.6.1/netcdf-fortran-4.6.1.zip -O -J
        unzip netcdf-fortran-4.6.1.zip

    - name: Setup oneAPI
      uses: ./modflow6/.github/actions/setup-par-oneapi

    - name: Build NetCDF
      shell: cmd
      run: |
        "%ONEAPI_ROOT%\setvars.bat" intel64 vs2022 && "%TEMP%\compile_netcdf.bat"
